"""Added some new fields and tokens

Revision ID: 483d36e4b426
Revises: c7fa8fa74240
Create Date: 2023-01-26 10:03:58.772780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483d36e4b426'
down_revision = 'c7fa8fa74240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('token_expiration', sa.DateTime(), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('token_expiration')
        batch_op.drop_column('token')
        batch_op.drop_column('phone')
        batch_op.drop_column('state')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
