"""Added image column to category table

Revision ID: 769953657290
Revises: 3e56582271fd
Create Date: 2023-02-08 18:00:43.272646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769953657290'
down_revision = '3e56582271fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=120), nullable=True))

    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_index('ix_food_food_name')
        batch_op.create_index(batch_op.f('ix_food_food_name'), ['food_name'], unique=False)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_index('ix_restaurant_restaurant_name')
        batch_op.create_index(batch_op.f('ix_restaurant_restaurant_name'), ['restaurant_name'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_last_name')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index('ix_user_last_name', ['last_name'], unique=False)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_restaurant_name'))
        batch_op.create_index('ix_restaurant_restaurant_name', ['restaurant_name'], unique=False)

    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_food_name'))
        batch_op.create_index('ix_food_food_name', ['food_name'], unique=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
