"""Added restaurants, food and orders

Revision ID: 7dcb14d53da6
Revises: 483d36e4b426
Create Date: 2023-01-30 20:32:35.245760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dcb14d53da6'
down_revision = '483d36e4b426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderDate', sa.DateTime(), nullable=True),
    sa.Column('orderTotal', sa.Float(), nullable=True),
    sa.Column('delivery_address', sa.String(length=120), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(length=120), nullable=True),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('street', sa.String(length=60), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_restaurant_name'), ['restaurant_name'], unique=False)

    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_food_name'), ['food_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_food_name'))

    op.drop_table('food')
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_restaurant_name'))

    op.drop_table('restaurant')
    op.drop_table('orders')
    # ### end Alembic commands ###
