"""Add favorites table

Revision ID: d16c2f75a443
Revises: 769953657290
Create Date: 2023-02-08 20:01:12.746862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16c2f75a443'
down_revision = '769953657290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=True),
    sa.Column('fk_restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_restaurant_id'], ['restaurant.id'], name=op.f('fk_favorites_fk_restaurant_id')),
    sa.ForeignKeyConstraint(['fk_user_id'], ['user.id'], name=op.f('fk_favorites_fk_user_id')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_index('ix_food_food_name')
        batch_op.create_index(batch_op.f('ix_food_food_name'), ['food_name'], unique=False)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_index('ix_restaurant_restaurant_name')
        batch_op.create_index(batch_op.f('ix_restaurant_restaurant_name'), ['restaurant_name'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.create_index('ix_user_email', ['email'], unique=False)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_restaurant_name'))
        batch_op.create_index('ix_restaurant_restaurant_name', ['restaurant_name'], unique=False)

    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_food_name'))
        batch_op.create_index('ix_food_food_name', ['food_name'], unique=False)

    op.drop_table('favorites')
    # ### end Alembic commands ###
