"""empty message

Revision ID: db6fbe9e2c7c
Revises: d16c2f75a443
Create Date: 2023-02-27 18:59:38.954176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6fbe9e2c7c'
down_revision = 'd16c2f75a443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_index('ix_food_food_name')
        batch_op.create_index(batch_op.f('ix_food_food_name'), ['food_name'], unique=False)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_index('ix_restaurant_restaurant_name')
        batch_op.create_index(batch_op.f('ix_restaurant_restaurant_name'), ['restaurant_name'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_token')
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_first_name'))
        batch_op.create_index('ix_user_token', ['token'], unique=False)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_restaurant_name'))
        batch_op.create_index('ix_restaurant_restaurant_name', ['restaurant_name'], unique=False)

    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_food_name'))
        batch_op.create_index('ix_food_food_name', ['food_name'], unique=False)

    # ### end Alembic commands ###
